pack:
	rm -rf xhamad03.zip
	zip -r xhamad03.zip dokumentace.pdf ESP32_PIR_motion_module/include ESP32_PIR_motion_module/lib ESP32_PIR_motion_module/platformio.ini ESP32_PIR_motion_module/src ESP32_Security_Camera/include/ ESP32_Security_Camera/lib ESP32_Security_Camera/platformio.ini ESP32_Security_Camera/src

