#!/bin/bash



# cast -h
print_help(){
    echo "Napoveda:"
    echo "      -h \ --help:"
    echo "                  zobrazi napovedu"
    echo "      [-g Group] FILE"
    echo "      [-m] [FILTERS] [DIRECTORY]"
    echo "      list [FILTERS] [DIRECTORY]"
    exit 0
}

error_func(){
    echo "Chybne zadane argumenty"
    exit 1
}
# list
list_function(){
    echo "list function TO-DO"
}
# secret-log
secret_log_function(){
    echo "secret-log function TO-DO"
}



# re-open file
re_open_file_function(){
    # nejprve zpracovat mozne kandidaty
    # potom az zvolit jestli last nebo most

    #zkontrolovat jestli mam neco po filtraci
    #pokud ne, nahlasit chybu a ukoncit skript

    # kontrola jestli otevrit posledni nebo nejvice otevirany
    if [ "$bool_MOST_EDITED" = true ]
    then
        echo "Most Edited"
    else
        echo "Last edited edited"
    fi
    echo "re-open function TO-DO"
}
# open file
open_file_function(){
    # kontrola, jestli ma spravny format
    if [[ $FILE_DIR == */ ]]
    then
        echo "Neplatny format jmena souboru (lomitko na konci)"
        exit 1
    fi
    # pokud soubor neexistuje
    if [ ! -e "$FILE_DIR" ]
    then
        mkdir -p "$(dirname "$FILE_DIR")" && touch "$FILE_DIR"
    fi
    #zprava pro log
    REAL_PATH="$(realpath $FILE_DIR)"
    REAL_DATE="$(date '+%Y-%m-%d %H-%M-%S')"
    echo "$REAL_PATH $REAL_DATE $GROUP" >> $MOLE_RC
    # otevrit soubor
    open_in_editor_function
    
}

# otevre soubor v zadanem editoru
open_in_editor_function(){
    if [[ -v EDITOR ]]
    then
        $EDITOR $REAL_PATH
    elif [[ -v VISUAL ]]
    then
        $VISUAL $REAL_PATH
    else
        vi $REAL_PATH
    fi
}

POSIXLY_CORRECT=yes

GROUP="-"
FILE_DIR=""

TIME_AFTER="1970-01-01"
TIME_BEFORE="9999-12-31"
bool_MOST_EDITED=false
bool_LIST=false
bool_SECRED_LOG=false

while [ "$#" -gt 0 ]; do
    case $1 in
        -h | --help)
            print_help
            ;;
        -g)
            GROUP=$2
            shift
            shift
            ;;
        -m)
            bool_MOST_EDITED=true
            shift
            ;;
        -a)
            TIME_AFTER=$2
            shift
            shift
            ;;
        -b)
            TIME_BEFORE=$2
            shift
            shift
            ;;
        list)
            bool_LIST=true
            shift
            ;;
        secret-log)
            bool_SECRED_LOG=true
            shift
            ;;
        *)
            if [ $# -gt 1 ]
            then
                error_func
            fi
            FILE_DIR=$1
            shift       
            ;;
    esac
done

#kontrola jestli je mole_rc definovano
if [[ ! -v MOLE_RC ]]
then
    echo "promena MOLE_RC neni nastavena"
    exit 1
else
    #vytvoreni $MOLE_RC pokud jeste neni
    if [ ! -e "$MOLE_RC" ]
    then
        echo "tvorim mole_rc"
        mkdir -p "$(dirname "$MOLE_RC")" && touch $MOLE_RC
    fi
fi

#kontrola kdyz jsou zadane oba
if [[ ("$bool_LIST" = true  &&  "$bool_SECRED_LOG" = true ) ]]
then
    echo "Neplatne parametry. (list a secret-log zaroven)"
    exit 1
fi 

# cast list
if [  "$bool_LIST" = true  ]
then
    echo "List"
    list_function
    exit 0
fi

# cast secret-log
if [  "$bool_SECRED_LOG" = true ]
then
    echo "Secret log"
    secret_log_function
    exit 0
fi

# zkontrolovat existenci [directory]
echo "Klasik editor"
if [ "$FILE_DIR" = "" ] || [[ -d $FILE_DIR ]]
then
    re_open_file_function
else
    open_file_function
fi