#!/bin/bash



# cast -h
print_help(){
    echo "Napoveda:"
    echo "      -h \ --help:"
    echo "                  zobrazi napovedu"
    echo "      [-g Group] FILE"
    echo "      [-m] [FILTERS] [DIRECTORY]"
    echo "      list [FILTERS] [DIRECTORY]"
    exit 0
}

error_func(){
    echo "Chybne zadane argumenty"
    exit 1
}

POSIXLY_CORRECT=yes

GROUP=""
FILE_DIR=""

TIME_AFTER="1970-01-01"
TIME_BEFORE="9999-12-31"
bool_MOST_EDITED=false
bool_LIST=false
bool_SECRED_LOG=false

while [ "$#" -gt 0 ]; do
    case $1 in
        -h | --help)
            print_help
            ;;
        -g)
            GROUP=$2
            shift
            shift
            ;;
        -m)
            bool_MOST_EDITED=true
            shift
            ;;
        -a)
            TIME_AFTER=$2
            shift
            shift
            ;;
        -b)
            TIME_BEFORE=$2
            shift
            shift
            ;;
        list)
            bool_LIST=true
            shift
            ;;
        secret-log)
            bool_SECRED_LOG=true
            shift
            ;;
        *)
            if [ $# -gt 1 ]
            then
                error_func
            fi
            FILE_DIR=$1
            shift       
            ;;
    esac
done

#kontrola jestli je mole_rc definovano
if [[ ! -v MOLE_RC ]]
then
    echo "promena MOLE_RC neni nastavena"
    exit 1
else
    if [ ! -e "$MOLE_RC" ]
    then
        mkdir -p "$(dirname "$MOLE_RC")" && touch $MOLE_RC
    fi
fi

#kontrola kdyz jsou zadane oba
if [[ ("$bool_LIST" = true  &&  "$bool_SECRED_LOG" = true ) ]]
then
    echo "Neplatne parametry. (list a secret-log zaroven)"
    exit 1
fi 

# cast list
if [  "$bool_LIST" = true  ]
then
    echo "List"
    exit 0
fi

# cast secret-log
if [  "$bool_SECRED_LOG" = true ]
then
    echo "Secret log"
    exit 0
fi

# zkontrolovat existenci [directory]
echo "Klasik editor"
if [ "$FILE_DIR" = "" ] || [[ -d $FILE_DIR ]]
then
    if [ "$bool_MOST_EDITED" = true ]
    then
        echo "Most Edited"
    else
        echo "Last edited edited"
    fi
else
    echo "Soubor"
fi